# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=+d,+xfauxhalf -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0x43,0x58,0x4c]
fmulex.s.h f6, f16, f5, rmm
# CHECK-ASM: encoding: [0xd3,0x0f,0x53,0x54]
fmacex.s.h f31, f6, f5, rne
# CHECK-ASM: encoding: [0xb3,0xaa,0x2e,0xbc]
vfsumex.s.h f21, f29, f2
# CHECK-ASM: encoding: [0x33,0x22,0x0e,0xbe]
vfnsumex.s.h f4, f28, f0
# CHECK-ASM: encoding: [0x33,0x2a,0x56,0x97]
vfdotpex.s.h f20, f12, f21
# CHECK-ASM: encoding: [0x33,0x62,0xe4,0x97]
vfdotpex.s.r.h f4, f8, f30
# CHECK-ASM: encoding: [0x33,0x25,0x5e,0xbb]
vfndotpex.s.h f10, f28, f21
# CHECK-ASM: encoding: [0x33,0x6f,0x5c,0xbb]
vfndotpex.s.r.h f30, f24, f21
