# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=+d,+xfauxquarter -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0x76,0x38,0x4f]
fmulex.s.b f12, f16, f19, dyn
# CHECK-ASM: encoding: [0xd3,0x14,0x66,0x57]
fmacex.s.b f9, f12, f22, rtz
# CHECK-ASM: encoding: [0xb3,0xb7,0x3b,0xbc]
vfsumex.h.b f15, f23, f3
# CHECK-ASM: encoding: [0x33,0x3d,0x23,0xbe]
vfnsumex.h.b f26, f6, f2
# CHECK-ASM: encoding: [0xb3,0xb3,0xf4,0x97]
vfdotpex.h.b f7, f9, f31
# CHECK-ASM: encoding: [0x33,0x7f,0x48,0x97]
vfdotpex.h.r.b f30, f16, f20
# CHECK-ASM: encoding: [0xb3,0x3f,0xe8,0xba]
vfndotpex.h.b f31, f16, f14
# CHECK-ASM: encoding: [0x33,0xf8,0x67,0xba]
vfndotpex.h.r.b f16, f15, f6
