# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=+d,+xfauxvecaltquarter -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x33,0xb3,0x63,0xbc]
vfsumex.ah.ab f6, f7, f6
# CHECK-ASM: encoding: [0x33,0x39,0x7f,0xbe]
vfnsumex.ah.ab f18, f30, f7
# CHECK-ASM: encoding: [0x33,0x3b,0x13,0x96]
vfdotpex.ah.ab f22, f6, f1
# CHECK-ASM: encoding: [0xb3,0xf5,0x6a,0x97]
vfdotpex.ah.r.ab f11, f21, f22
# CHECK-ASM: encoding: [0x33,0x39,0xd9,0xba]
vfndotpex.ah.ab f18, f18, f13
# CHECK-ASM: encoding: [0x33,0x76,0xb5,0xbb]
vfndotpex.ah.r.ab f12, f10, f27
