# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=+d,+xfauxalthalf -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0xd3,0xc5,0x1d,0x4c]
fmulex.s.ah f11, f27, f1, rmm
# CHECK-ASM: encoding: [0x53,0x85,0xe3,0x54]
fmacex.s.ah f10, f7, f14, rne
# CHECK-ASM: encoding: [0xb3,0x2b,0x3c,0xbc]
vfsumex.s.ah f23, f24, f3
# CHECK-ASM: encoding: [0xb3,0xa2,0xd9,0xbf]
vfnsumex.s.ah f5, f19, f29
# CHECK-ASM: encoding: [0x33,0x2e,0x77,0x96]
vfdotpex.s.ah f28, f14, f7
# CHECK-ASM: encoding: [0x33,0xe8,0x7e,0x97]
vfdotpex.s.r.ah f16, f29, f23
# CHECK-ASM: encoding: [0x33,0xa8,0x3c,0xba]
vfndotpex.s.ah f16, f25, f3
# CHECK-ASM: encoding: [0xb3,0x65,0x69,0xba]
vfndotpex.s.r.ah f11, f18, f6
