# Automatically generated by parse_opcodes (noah95/riscv-opcodes)
# RUN: llvm-mc %s -triple=riscv64 -mattr=+d,+xfauxaltquarter -riscv-no-aliases -show-encoding \
# RUN:     | FileCheck -check-prefixes=CHECK-ASM %s

# CHECK-ASM: encoding: [0x53,0xc2,0xb6,0x4e]
fmulex.s.ab f4, f13, f11, rmm
# CHECK-ASM: encoding: [0x53,0x3a,0x5b,0x57]
fmacex.s.ab f20, f22, f21, rup
# CHECK-ASM: encoding: [0x33,0x30,0x8c,0xbc]
vfsumex.h.ab f0, f24, f8
# CHECK-ASM: encoding: [0x33,0xb1,0x7f,0xbf]
vfnsumex.h.ab f2, f31, f23
# CHECK-ASM: encoding: [0x33,0x36,0x1e,0x97]
vfdotpex.h.ab f12, f28, f17
# CHECK-ASM: encoding: [0xb3,0x7c,0x84,0x96]
vfdotpex.h.r.ab f25, f8, f8
# CHECK-ASM: encoding: [0x33,0xbf,0xbe,0xba]
vfndotpex.h.ab f30, f29, f11
# CHECK-ASM: encoding: [0xb3,0x75,0x3a,0xbb]
vfndotpex.h.r.ab f11, f20, f19
